version: "3.9"

services:
    nginx: 
        container_name: cs_nginx
        restart: always
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile.prod
        ports:
            - 80:80
        volumes:
            - static_volume:/srv/app/django_static
        depends_on: 
            - server
    server:
        container_name: cs_server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        volumes:
            - static_volume:/srv/app/django_static   
        entrypoint: /srv/app/wsgi-entrypoint.sh
        ports:
            - 8000:8000        
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: cs_postgres
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=db_name
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
        ports:
            - 5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    static_volume: {}