version: "3.9"
   
services:
  postgres:
    container_name: cs_postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # mongo:
  #   container_name: cs_mongo
  #   image: mongo
  #   volumes:
  #     - ./data/db:/data/db
  #   ports: 
  #     - 27017:27017
  #   environment:
  #       - MONGO_INITDB_ROOT_USERNAME=db_user
  #       - MONGO_INITDB_ROOT_PASSWORD=db_password
  #       - MONGO_INITDB_DATABASE=db_name
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 40s
  
  server:
    container_name: cs_server
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/srv/app
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  client:
    container_name: cs_client
    build: ./client
    volumes:
      - /client/node_modules
    ports:
      - 3000:3000