version: "3.9"
   
services:
  postgres:
    container_name: cs_postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    container_name: cs_server
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/srv/app
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  client:
    container_name: cs_client
    build: ./client
    volumes:
      - /client/node_modules
    ports:
      - 3000:3000